-- Baseline copied from the supplied database. Existing tables are preserved.
CREATE TABLE IF NOT EXISTS Shops (ID INTEGER PRIMARY KEY UNIQUE NOT NULL, shop_name TEXT NOT NULL, shop_address TEXT, shop_create_date INTEGER, shop_update_date INTEGER);
CREATE TABLE IF NOT EXISTS ItemsInvoices (ID INTEGER PRIMARY KEY NOT NULL UNIQUE, item_id INTEGER REFERENCES Items (ID), invoice_id INTEGER REFERENCES Invoices (ID), iteminvoice_create_date INTEGER, iteminvoice_update_date INTEGER, iteminvoice_nr INTEGER, iteminvoice_weight INTEGER);
CREATE TABLE IF NOT EXISTS Manufactures (ID INTEGER PRIMARY KEY UNIQUE NOT NULL, manufacturer_name TEXT, manufacturer_create_date INTEGER, manufacturer_update_date INTEGER);
CREATE TABLE IF NOT EXISTS Users (ID INTEGER PRIMARY KEY UNIQUE NOT NULL, user_username TEXT NOT NULL UNIQUE, user_email TEXT NOT NULL UNIQUE, user_name TEXT, user_lastname TEXT, user_avatar TEXT DEFAULT 'https://api.dicebear.com/7.x/avataaars/svg?seed=undefined', user_password BLOB, user_oidc_provider TEXT, userrole_id INTEGER REFERENCES UserRoles (ID), user_create_date INTEGER, user_update_date INTEGER, user_font_family TEXT DEFAULT 'sans', user_font_size INTEGER DEFAULT 18, user_theme TEXT DEFAULT 'light');
CREATE TABLE IF NOT EXISTS UserRoles (ID INTEGER PRIMARY KEY UNIQUE NOT NULL, userrole_name TEXT NOT NULL UNIQUE, userrole_description TEXT, userrole_manageusers INTEGER DEFAULT 0, userrole_manageshops INTEGER DEFAULT 0, userrole_managemanufactures INTEGER DEFAULT 0, userrole_create_date INTEGER, userrole_update_date INTEGER);
CREATE TABLE IF NOT EXISTS ItemTypes (ID INTEGER PRIMARY KEY UNIQUE NOT NULL, itemtype_name TEXT NOT NULL, itemtype_description TEXT, itemtype_createdate INTEGER, itemtype_updatedate INTEGER);
CREATE TABLE IF NOT EXISTS Invoices (ID INTEGER PRIMARY KEY UNIQUE NOT NULL, invoice_date INTEGER NOT NULL, invoice_create_date INTEGER, invoice_update_date INTEGER, shop_id INTEGER REFERENCES Shops (ID), user_id INTEGER REFERENCES Users (ID));
CREATE TABLE IF NOT EXISTS Items (ID INTEGER PRIMARY KEY NOT NULL UNIQUE, item_name TEXT NOT NULL, item_description TEXT, item_create_date INTEGER, item_update_date INTEGER, itemtype_id INTEGER REFERENCES ItemTypes (ID), manufacturer_id INTEGER REFERENCES Manufactures (ID));
